{
 "title": "UPF GTP5G Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Interface RX/TX bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(free5gc_upf_interface_rx_bytes_total[1m]) * 8",
     "legendFormat": "RX {{interface}}"
    },
    {
     "expr": "rate(free5gc_upf_interface_tx_bytes_total[1m]) * 8",
     "legendFormat": "TX {{interface}}"
    }
   ]
  },
  {
   "title": "UL Throughput per UE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by (ue_addr) (rate(free5gc_upf_gtp_ul_bytes_total{ue_addr!=\"<none>\"}[1m])) * 8",
     "legendFormat": "{{ue_addr}}"
    }
   ]
  },
  {
   "title": "UL/DL Packets per UE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by (ue_addr) (rate(free5gc_upf_gtp_ul_packets_total{ue_addr!=\"<none>\"}[1m]))",
     "legendFormat": "UL {{ue_addr}}"
    },
    {
     "expr": "sum by (ue_addr) (rate(free5gc_upf_gtp_dl_packets_total{ue_addr!=\"<none>\"}[1m]))",
     "legendFormat": "DL {{ue_addr}}"
    }
   ]
  },
  {
   "title": "DL Throughput per UE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by (ue_addr) (rate(free5gc_upf_gtp_dl_bytes_total{ue_addr!=\"<none>\"}[1m])) * 8",
     "legendFormat": "{{ue_addr}}"
    }
   ]
  },
  {
   "title": "Active UE Session(s)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (seid) (free5gc_upf_gtp_ul_bytes_total))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}