apiVersion: v2
name: free5gc-k8s
description: Free5GC v4.2 on Kubernetes with Cilium CNI, Multus, and Hubble observability
version: 0.1.0
appVersion: "v4.2.0"
maintainers:
  - name: Idemudia Charles Okojie
    email: ideco001@hotmail.com
    url: https://github.com/Charlz234

