global:
  name: free5gc
  namespace: free5gc
  plmn:
    mcc: "208"
    mnc: "93"

mongodb:
  service:
    port: 27017

amf:
  image:
    repository: ghcr.io/charlz234/free5gc-amf
    tag: v4.2.0-metrics
  replicas: 1
  hostIP: 10.0.2.3
  n2:
    port: 38412
  metrics:
    enabled: true
    port: 9089

ausf:
  image:
    repository: ghcr.io/charlz234/free5gc-ausf
    tag: v4.2.0-metrics
  replicas: 1
  metrics:
    enabled: true
    port: 9089

nef:
  image:
    repository: free5gc/nef
    tag: v4.2.0
  replicas: 1
  metrics:
    enabled: false
    port: 9089

nrf:
  image:
    repository: ghcr.io/charlz234/free5gc-nrf
    tag: v4.2.0-metrics
  replicas: 1
  metrics:
    enabled: true
    port: 9089

nssf:
  image:
    repository: ghcr.io/charlz234/free5gc-nssf
    tag: v4.2.0-metrics
  replicas: 1
  metrics:
    enabled: true
    port: 9089

pcf:
  image:
    repository: ghcr.io/charlz234/free5gc-pcf
    tag: v4.2.0-metrics
  replicas: 1
  metrics:
    enabled: true
    port: 9089

smf:
  image:
    repository: ghcr.io/charlz234/free5gc-smf
    tag: v4.2.0-metrics
  replicas: 1
  pfcp:
    hostIP: 10.0.2.3
  metrics:
    enabled: true
    port: 9089

udm:
  image:
    repository: ghcr.io/charlz234/free5gc-udm
    tag: v4.2.0-metrics
  replicas: 1
  metrics:
    enabled: true
    port: 9089

udr:
  image:
    repository: ghcr.io/charlz234/free5gc-udr
    tag: v4.2.0-metrics
  replicas: 1
  metrics:
    enabled: true
    port: 9089

upf:
  image:
    repository: free5gc/upf
    tag: v4.2.0
  replicas: 1
  pfcp:
    hostIP: 10.0.2.3
  gtp:
    hostIP: 10.0.2.3
  metrics:
    enabled: false
    port: 9089

webui:
  image:
    repository: free5gc/webui
    tag: v4.2.0
  replicas: 1