apiVersion: apps/v1
kind: Deployment
metadata:
  name: amf
  namespace: {{ .Values.global.namespace }}
  labels:
    app: amf
spec:
  replicas: {{ .Values.amf.replicas }}
  selector:
    matchLabels:
      app: amf
  template:
    metadata:
      labels:
        app: amf
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: amf
          image: {{ .Values.amf.image.repository }}:{{ .Values.amf.image.tag }}
          command: ["./amf", "-c", "./config/amfcfg.yaml"]
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          ports:
            - name: sbi
              containerPort: 8018
            {{- if .Values.amf.metrics.enabled }}
            - name: metrics
              containerPort: {{ .Values.amf.metrics.port }}
            {{- end }}
          volumeMounts:
            - name: config
              mountPath: /free5gc/config/amfcfg.yaml
              subPath: amfcfg.yaml
      volumes:
        - name: config
          configMap:
            name: amf-config
---
apiVersion: v1
kind: Service
metadata:
  name: amf-namf
  namespace: {{ .Values.global.namespace }}
  labels:
    app: amf
spec:
  selector:
    app: amf
  ports:
    - name: sbi
      port: 8018
      targetPort: 8018
    {{- if .Values.amf.metrics.enabled }}
    - name: metrics
      port: {{ .Values.amf.metrics.port }}
      targetPort: {{ .Values.amf.metrics.port }}
    {{- end }}
  type: ClusterIP