apiVersion: apps/v1
kind: Deployment
metadata:
  name: ausf
  namespace: {{ .Values.global.namespace }}
  labels:
    app: ausf
spec:
  replicas: {{ .Values.ausf.replicas }}
  selector:
    matchLabels:
      app: ausf
  template:
    metadata:
      labels:
        app: ausf
    spec:
      containers:
        - name: ausf
          image: {{ .Values.ausf.image.repository }}:{{ .Values.ausf.image.tag }}
          command: ["./ausf", "-c", "./config/ausfcfg.yaml"]
          ports:
            - name: sbi
              containerPort: 8000
            {{- if .Values.ausf.metrics.enabled }}
            - name: metrics
              containerPort: {{ .Values.ausf.metrics.port }}
            {{- end }}
          volumeMounts:
            - name: config
              mountPath: /free5gc/config/ausfcfg.yaml
              subPath: ausfcfg.yaml
      volumes:
        - name: config
          configMap:
            name: ausf-config
---
apiVersion: v1
kind: Service
metadata:
  name: ausf-nausf
  namespace: {{ .Values.global.namespace }}
  labels:
    app: ausf
spec:
  selector:
    app: ausf
  ports:
    - name: sbi
      port: 8000
      targetPort: 8000
    {{- if .Values.ausf.metrics.enabled }}
    - name: metrics
      port: {{ .Values.ausf.metrics.port }}
      targetPort: {{ .Values.ausf.metrics.port }}
    {{- end }}
  type: ClusterIP