apiVersion: v1
kind: ConfigMap
metadata:
  name: nef-config
  namespace: free5gc
data:
  nefcfg.yaml: |
    info:
      version: 1.0.1
      description: NEF initial local configuration
    configuration:
      sbi:
        scheme: http
        registerIPv4: nef-nnef
        bindingIPv4: 0.0.0.0
        port: 8000
      nrfUri: http://nrf-nnrf:8000
      serviceList:
        - serviceName: nnef-pfdmanagement
        - serviceName: nnef-oam
      metrics:
        enable: false
        scheme: http
        bindingIPv4: 0.0.0.0
        port: 9089
    logger:
      enable: true
      level: info
      reportCaller: false