apiVersion: apps/v1
kind: Deployment
metadata:
  name: nef
  namespace: {{ .Values.global.namespace }}
  labels:
    app: nef
spec:
  replicas: {{ .Values.nef.replicas }}
  selector:
    matchLabels:
      app: nef
  template:
    metadata:
      labels:
        app: nef
    spec:
      containers:
        - name: nef
          image: {{ .Values.nef.image.repository }}:{{ .Values.nef.image.tag }}
          command: ["./nef", "-c", "./config/nefcfg.yaml"]
          ports:
            - name: sbi
              containerPort: 8000
            {{- if .Values.nef.metrics.enabled }}
            - name: metrics
              containerPort: {{ .Values.nef.metrics.port }}
            {{- end }}
          volumeMounts:
            - name: config
              mountPath: /free5gc/config/nefcfg.yaml
              subPath: nefcfg.yaml
      volumes:
        - name: config
          configMap:
            name: nef-config
---
apiVersion: v1
kind: Service
metadata:
  name: nef-nnef
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: nef
  ports:
    - name: sbi
      port: 8000
      targetPort: 8000
    {{- if .Values.nef.metrics.enabled }}
    - name: metrics
      port: {{ .Values.nef.metrics.port }}
      targetPort: {{ .Values.nef.metrics.port }}
    {{- end }}
  type: ClusterIP