apiVersion: apps/v1
kind: Deployment
metadata:
  name: nrf
  namespace: {{ .Values.global.namespace }}
  labels:
    app: nrf
spec:
  replicas: {{ .Values.nrf.replicas }}
  selector:
    matchLabels:
      app: nrf
  template:
    metadata:
      labels:
        app: nrf
    spec:
      containers:
        - name: nrf
          image: {{ .Values.nrf.image.repository }}:{{ .Values.nrf.image.tag }}
          command: ["./nrf", "-c", "./config/nrfcfg.yaml"]
          ports:
            - name: sbi
              containerPort: 8000
            {{- if .Values.nrf.metrics.enabled }}
            - name: metrics
              containerPort: {{ .Values.nrf.metrics.port }}
            {{- end }}
          volumeMounts:
            - name: config
              mountPath: /free5gc/config/nrfcfg.yaml
              subPath: nrfcfg.yaml
      volumes:
        - name: config
          configMap:
            name: nrf-config
---
apiVersion: v1
kind: Service
metadata:
  name: nrf-nnrf
  namespace: {{ .Values.global.namespace }}
  labels:
    app: nrf
spec:
  selector:
    app: nrf
  ports:
    - name: sbi
      port: 8000
      targetPort: 8000
    {{- if .Values.nrf.metrics.enabled }}
    - name: metrics
      port: {{ .Values.nrf.metrics.port }}
      targetPort: {{ .Values.nrf.metrics.port }}
    {{- end }}
  type: ClusterIP