apiVersion: v1
kind: ConfigMap
metadata:
  name: nrf-config
  namespace: free5gc
data:
  nrfcfg.yaml: |
    info:
      version: 1.0.2
      description: NRF initial local configuration
    configuration:
      MongoDBName: free5gc
      MongoDBUrl: mongodb://mongodb:27017
      sbi:
        scheme: http
        registerIPv4: nrf-nnrf
        bindingIPv4: 0.0.0.0
        port: 8000
      DefaultPlmnId:
        mcc: "208"
        mnc: "93"
      serviceNameList:
        - nnrf-nfm
        - nnrf-disc
    logger:
      enable: true
      level: info
      reportCaller: false
    metrics:
      enable: true
      scheme: http
      bindingIPv4: 0.0.0.0
      port: 9089