apiVersion: apps/v1
kind: Deployment
metadata:
  name: nssf
  namespace: free5gc
  labels:
    app: nssf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nssf
  template:
    metadata:
      labels:
        app: nssf
    spec:
      containers:
        - name: nssf
          image: free5gc/nssf:v4.2.0
          command: ["./nssf", "-c", "./config/nssfcfg.yaml"]
          volumeMounts:
            - name: config
              mountPath: /free5gc/config/nssfcfg.yaml
              subPath: nssfcfg.yaml
      volumes:
        - name: config
          configMap:
            name: nssf-config
---
apiVersion: v1
kind: Service
metadata:
  name: nssf-nnssf
  namespace: free5gc
spec:
  selector:
    app: nssf
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP
