apiVersion: apps/v1
kind: Deployment
metadata:
  name: nssf
  namespace: {{ .Values.global.namespace }}
  labels:
    app: nssf
spec:
  replicas: {{ .Values.nssf.replicas }}
  selector:
    matchLabels:
      app: nssf
  template:
    metadata:
      labels:
        app: nssf
    spec:
      containers:
        - name: nssf
          image: {{ .Values.nssf.image.repository }}:{{ .Values.nssf.image.tag }}
          command: ["./nssf", "-c", "./config/nssfcfg.yaml"]
          ports:
            - name: sbi
              containerPort: 8000
            {{- if .Values.nssf.metrics.enabled }}
            - name: metrics
              containerPort: {{ .Values.nssf.metrics.port }}
            {{- end }}
          volumeMounts:
            - name: config
              mountPath: /free5gc/config/nssfcfg.yaml
              subPath: nssfcfg.yaml
      volumes:
        - name: config
          configMap:
            name: nssf-config
---
apiVersion: v1
kind: Service
metadata:
  name: nssf-nnssf
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: nssf
  ports:
    - name: sbi
      port: 8000
      targetPort: 8000
    {{- if .Values.nssf.metrics.enabled }}
    - name: metrics
      port: {{ .Values.nssf.metrics.port }}
      targetPort: {{ .Values.nssf.metrics.port }}
    {{- end }}
  type: ClusterIP