apiVersion: apps/v1
kind: Deployment
metadata:
  name: pcf
  namespace: free5gc
  labels:
    app: pcf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pcf
  template:
    metadata:
      labels:
        app: pcf
    spec:
      containers:
        - name: pcf
          image: free5gc/pcf:v4.2.0
          command: ["./pcf", "-c", "./config/pcfcfg.yaml"]
          volumeMounts:
            - name: config
              mountPath: /free5gc/config/pcfcfg.yaml
              subPath: pcfcfg.yaml
      volumes:
        - name: config
          configMap:
            name: pcf-config
---
apiVersion: v1
kind: Service
metadata:
  name: pcf-npcf
  namespace: free5gc
spec:
  selector:
    app: pcf
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP
