apiVersion: apps/v1
kind: Deployment
metadata:
  name: pcf
  namespace: {{ .Values.global.namespace }}
  labels:
    app: pcf
spec:
  replicas: {{ .Values.pcf.replicas }}
  selector:
    matchLabels:
      app: pcf
  template:
    metadata:
      labels:
        app: pcf
    spec:
      containers:
        - name: pcf
          image: {{ .Values.pcf.image.repository }}:{{ .Values.pcf.image.tag }}
          command: ["./pcf", "-c", "./config/pcfcfg.yaml"]
          ports:
            - name: sbi
              containerPort: 8000
            {{- if .Values.pcf.metrics.enabled }}
            - name: metrics
              containerPort: {{ .Values.pcf.metrics.port }}
            {{- end }}
          volumeMounts:
            - name: config
              mountPath: /free5gc/config/pcfcfg.yaml
              subPath: pcfcfg.yaml
      volumes:
        - name: config
          configMap:
            name: pcf-config
---
apiVersion: v1
kind: Service
metadata:
  name: pcf-npcf
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: pcf
  ports:
    - name: sbi
      port: 8000
      targetPort: 8000
    {{- if .Values.pcf.metrics.enabled }}
    - name: metrics
      port: {{ .Values.pcf.metrics.port }}
      targetPort: {{ .Values.pcf.metrics.port }}
    {{- end }}
  type: ClusterIP