apiVersion: apps/v1
kind: Deployment
metadata:
  name: smf
  namespace: {{ .Values.global.namespace }}
  labels:
    app: smf
spec:
  replicas: {{ .Values.smf.replicas }}
  selector:
    matchLabels:
      app: smf
  template:
    metadata:
      labels:
        app: smf
    spec:
      containers:
        - name: smf
          image: {{ .Values.smf.image.repository }}:{{ .Values.smf.image.tag }}
          command: ["./smf", "-c", "./config/smfcfg.yaml"]
          ports:
            - name: sbi
              containerPort: 8000
            {{- if .Values.smf.metrics.enabled }}
            - name: metrics
              containerPort: {{ .Values.smf.metrics.port }}
            {{- end }}
          volumeMounts:
            - name: config
              mountPath: /free5gc/config/smfcfg.yaml
              subPath: smfcfg.yaml
            - name: config
              mountPath: /free5gc/config/uerouting.yaml
              subPath: uerouting.yaml
      volumes:
        - name: config
          configMap:
            name: smf-config
---
apiVersion: v1
kind: Service
metadata:
  name: smf-nsmf
  namespace: {{ .Values.global.namespace }}
  labels:
    app: smf
spec:
  selector:
    app: smf
  ports:
    - name: sbi
      port: 8000
      targetPort: 8000
    {{- if .Values.smf.metrics.enabled }}
    - name: metrics
      port: {{ .Values.smf.metrics.port }}
      targetPort: {{ .Values.smf.metrics.port }}
    {{- end }}
  type: ClusterIP