apiVersion: v1
kind: ConfigMap
metadata:
  name: smf-config
  namespace: free5gc
data:
  smfcfg.yaml: |
    info:
      version: 1.0.7
      description: SMF initial local configuration
    configuration:
      smfName: SMF
      sbi:
        scheme: http
        registerIPv4: smf-nsmf
        bindingIPv4: 0.0.0.0
        port: 8000
      serviceNameList:
        - nsmf-pdusession
        - nsmf-event-exposure
        - nsmf-oam
      snssaiInfos:
        - sNssai:
            sst: 1
            sd: 010203
          dnnInfos:
            - dnn: internet
              dns:
                ipv4: 8.8.8.8
                ipv6: 2001:4860:4860::8888
        - sNssai:
            sst: 1
            sd: 112233
          dnnInfos:
            - dnn: internet
              dns:
                ipv4: 8.8.8.8
                ipv6: 2001:4860:4860::8888
      plmnList:
        - mcc: 208
          mnc: 93
      locality: area1
      pfcp:
        nodeID: 10.43.5.178
        listenAddr: 0.0.0.0
        externalAddr: 10.43.5.178
      userplaneInformation:
        upNodes:
          gNB1:
            type: AN
          UPF:
            type: UPF
            nodeID: upf-pfcp
            addr: upf-pfcp
            sNssaiUpfInfos:
              - sNssai:
                  sst: 1
                  sd: 010203
                dnnUpfInfoList:
                  - dnn: internet
                    pools:
                      - cidr: 10.60.0.0/16
                    staticPools:
                      - cidr: 10.60.100.0/24
              - sNssai:
                  sst: 1
                  sd: 112233
                dnnUpfInfoList:
                  - dnn: internet
                    pools:
                      - cidr: 10.61.0.0/16
                    staticPools:
                      - cidr: 10.61.100.0/24
            interfaces:
              - interfaceType: N3
                endpoints:
                  - 10.0.2.3
                networkInstances:
                  - internet
        links:
          - A: gNB1
            B: UPF
      t3591:
        enable: true
        expireTime: 16s
        maxRetryTimes: 3
      t3592:
        enable: true
        expireTime: 16s
        maxRetryTimes: 3
      nrfUri: http://nrf-nnrf:8000
      urrPeriod: 10
      urrThreshold: 1000
      requestedUnit: 1000
    logger:
      enable: true
      level: info
      reportCaller: false
    metrics:
      enable: true
      scheme: http
      bindingIPv4: 0.0.0.0
      port: 9089
  uerouting.yaml: |
    info:
      version: 1.0.7
      description: Routing information for UE
    ueRoutingInfo:
      UE1:
        members:
          - imsi-208930000000001
        topology:
          - A: gNB1
            B: UPF
        specificPath: []