apiVersion: apps/v1
kind: Deployment
metadata:
  name: udr
  namespace: {{ .Values.global.namespace }}
  labels:
    app: udr
spec:
  replicas: {{ .Values.udr.replicas }}
  selector:
    matchLabels:
      app: udr
  template:
    metadata:
      labels:
        app: udr
    spec:
      containers:
        - name: udr
          image: {{ .Values.udr.image.repository }}:{{ .Values.udr.image.tag }}
          command: ["./udr", "-c", "./config/udrcfg.yaml"]
          ports:
            - name: sbi
              containerPort: 8000
            {{- if .Values.udr.metrics.enabled }}
            - name: metrics
              containerPort: {{ .Values.udr.metrics.port }}
            {{- end }}
          volumeMounts:
            - name: config
              mountPath: /free5gc/config/udrcfg.yaml
              subPath: udrcfg.yaml
      volumes:
        - name: config
          configMap:
            name: udr-config
---
apiVersion: v1
kind: Service
metadata:
  name: udr-nudr
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: udr
  ports:
    - name: sbi
      port: 8000
      targetPort: 8000
    {{- if .Values.udr.metrics.enabled }}
    - name: metrics
      port: {{ .Values.udr.metrics.port }}
      targetPort: {{ .Values.udr.metrics.port }}
    {{- end }}
  type: ClusterIP