apiVersion: apps/v1
kind: Deployment
metadata:
  name: upf
  namespace: {{ .Values.global.namespace }}
  labels:
    app: upf
spec:
  replicas: {{ .Values.upf.replicas }}
  selector:
    matchLabels:
      app: upf
  template:
    metadata:
      labels:
        app: upf
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      initContainers:
        - name: iptables-init
          image: {{ .Values.upf.image.repository }}:{{ .Values.upf.image.tag }}
          command: ["bash", "/free5gc/config/upf-iptables.sh"]
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          volumeMounts:
            - name: config
              mountPath: /free5gc/config/upf-iptables.sh
              subPath: upf-iptables.sh
      containers:
        - name: upf
          image: {{ .Values.upf.image.repository }}:{{ .Values.upf.image.tag }}
          command: ["./upf", "-c", "./config/upfcfg.yaml"]
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          {{- if .Values.upf.metrics.enabled }}
          ports:
            - name: metrics
              containerPort: {{ .Values.upf.metrics.port }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /free5gc/config/upfcfg.yaml
              subPath: upfcfg.yaml
      volumes:
        - name: config
          configMap:
            name: upf-config
---
apiVersion: v1
kind: Service
metadata:
  name: upf-pfcp
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: upf
  clusterIP: None
  ports:
    - name: pfcp
      port: 8805
      targetPort: 8805
      protocol: UDP