apiVersion: apps/v1
kind: Deployment
metadata:
  name: upf
  namespace: free5gc
  labels:
    app: upf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: upf
  template:
    metadata:
      labels:
        app: upf
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      initContainers:
        - name: iptables-init
          image: free5gc/upf:v4.2.0
          command: ["bash", "/free5gc/config/upf-iptables.sh"]
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          volumeMounts:
            - name: config
              mountPath: /free5gc/config/upf-iptables.sh
              subPath: upf-iptables.sh
      containers:
        - name: upf
          image: free5gc/upf:v4.2.0
          command: ["./upf", "-c", "./config/upfcfg.yaml"]
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          volumeMounts:
            - name: config
              mountPath: /free5gc/config/upfcfg.yaml
              subPath: upfcfg.yaml
      volumes:
        - name: config
          configMap:
            name: upf-config
---
apiVersion: v1
kind: Service
metadata:
  name: upf-pfcp
  namespace: free5gc
spec:
  selector:
    app: upf
  clusterIP: None
  ports:
    - name: pfcp
      port: 8805
      targetPort: 8805
      protocol: UDP
